# Generated by Django 6.0.5 on 2026-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the description or title of the task you want to complete.', max_length=200, verbose_name='Task Title')),
                ('is_completed', models.BooleanField(default=False, help_text='Check this box if the task has been fully completed.', verbose_name='Is Completed?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The exact date and time this task was registered on the board.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
